//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MC_Validation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MC_Validation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;help&gt;
        ///  &lt;g&gt;
        ///    &lt;![CDATA[
        ///&apos;******************************************************************************************
        ///&apos; MC_Validation help.xml  
        ///&apos;-----------------------------------------------------------------------
        ///
        ///&apos;------------------------------------------------------------------------
        ///
        ///]]&gt;
        ///  &lt;/g&gt;
        ///  
        ///  &lt;ref id=&quot;UpdateCredentialList&quot;&gt;
        ///    &lt;p name=&quot;sCredential&quot;/&gt;
        ///    &lt;p name=&quot;AddRemove&quot;/&gt;
        ///    &lt;ap&gt;
        ///      A two parameter specification of a list of credential abbreviations and a Add or Rem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; ?&gt;
        ///&lt;rrx namespace=&quot;MC_Validation&quot;&gt;
        ///&lt;i ref=&quot;rrunner&quot;/&gt;&lt;g&gt;
        ///  &lt;![CDATA[
        ///&apos;******************************************************************************************
        ///&apos; MC_Validation.rra - Validation Medical Claims Actions 
        ///&apos;-----------------------------------------------------------------------
        ///
        ///&apos;-----------------------------------------------------------------------------------------
        ///Writelog(&quot;MC_Validation dll_AssemblyVersion&quot;)
        ///&apos;**************************************************** [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MC_Validation {
            get {
                return ResourceManager.GetString("MC_Validation", resourceCulture);
            }
        }
    }
}
